name: Android CI

on:
  push:
    branches:
      - "master"
      - "docs/actions"
    paths-ignore:
      - README.md
      - xd/**
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - xd/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: set up AD_UNIT_ID
        run: echo "AD_UNIT_ID=``" >> local.properties

      - name: set up AD_APPLICATION_ID
        run: echo "AD_APPLICATION_ID=``" >> local.properties

      - name: set up google-service.json
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
