name: ktlint CI

on:
  push:
    branches:
      - "master"
      - "docs/actions"
    paths-ignore:
      - README.md
      - xd/**
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - README.md
      - xd/**

jobs:
  ktlint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up AD_UNIT_ID
        run: echo "AD_UNIT_ID=``" >> local.properties

      - name: set up AD_APPLICATION_ID
        run: echo "AD_APPLICATION_ID=``" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlint